In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:

# Configurações de conexão com o banco de dados PostgreSQL
DB_USER = 'postgres'
DB_PASSWORD = 'dragon'
DB_HOST = 'localhost'
DB_PORT = '5434'
DB_NAME = 'postgres'


# Conecta ao banco de dados PostgreSQL
engine = create_engine(f'postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}')

# Extrai os dados de uma tabela específica
#query = "SELECT * FROM sua_tabela"
#df = pd.read_sql(query, engine)

# Realiza qualquer transformação necessária nos dados
# Por exemplo, converte colunas de datas para o formato correto
# df['data'] = pd.to_datetime(df['data'])

# Carrega os dados transformados em outra tabela do PostgreSQL
# Substitua 'tabela_destino' pelo nome da tabela de destino no seu banco de dados
# df.to_sql('tabela_destino', engine, index=False, if_exists='replace')

# Se preferir, pode também salvar os dados em outro formato, como CSV
# df.to_csv('dados_transformados.csv', index=False)

In [3]:
df_campeonato_brasileiro_cartoes = pd.read_csv(r'C:\Users\gusta\Documents\TCC\campeonato-brasileiro-cartoes.csv')
df_campeonato_brasileiro_estatisticas_full = pd.read_csv(r'C:\Users\gusta\Documents\TCC\campeonato-brasileiro-estatisticas-full.csv')
df_campeonato_brasileiro_full = pd.read_csv(r'C:\Users\gusta\Documents\TCC\campeonato-brasileiro-full.csv')
df_campeonato_brasileiro_gols = pd.read_csv(r'C:\Users\gusta\Documents\TCC\campeonato-brasileiro-gols.csv')

In [5]:
df_campeonato_brasileiro_cartoes.rename(columns={'rodata': 'rodada'}, inplace=True) 

TABLE_NAME = 'campeonato_brasileiro_cartoes'

df_campeonato_brasileiro_cartoes.to_sql(TABLE_NAME, engine, index=False, if_exists='replace')

In [30]:
df_campeonato_brasileiro_estatisticas_full.rename(columns={'rodata': 'rodada'}, inplace=True) 

TABLE_NAME = 'campeonato_brasileiro_estatisticas_full'

df_campeonato_brasileiro_estatisticas_full.to_sql(TABLE_NAME, engine, index=False, if_exists='replace')

In [32]:
df_campeonato_brasileiro_full.rename(columns={'rodata': 'rodada'}, inplace=True) 

TABLE_NAME = 'campeonato_brasileiro_full'

df_campeonato_brasileiro_full.to_sql(TABLE_NAME, engine, index=False, if_exists='replace')

In [34]:
df_campeonato_brasileiro_gols.rename(columns={'rodata': 'rodada'}, inplace=True) 

TABLE_NAME = 'campeonato_brasileiro_gols'


df_campeonato_brasileiro_gols.to_sql(TABLE_NAME, engine, index=False, if_exists='replace')

In [3]:
df_lat_long = pd.read_csv(r'C:\Users\gusta\Documents\TCC\brasil.csv')

df_lat_long = df_lat_long.drop('capital', axis=1)
df_lat_long = df_lat_long.drop('ibge', axis=1)
df_lat_long = df_lat_long.drop('cod_estado', axis=1)

TABLE_NAME = 'latlong'
df_lat_long.to_sql(TABLE_NAME, engine, index=False, if_exists='replace')

In [28]:
df_camp20032022_classificacao = pd.read_csv(r'C:\Users\gusta\OneDrive\Área de Trabalho\TCC\df_classificacao.csv')
df_camp20032022_rodadas = pd.read_csv(r'C:\Users\gusta\OneDrive\Área de Trabalho\TCC\df_rodadas.csv')
df_camp23_classificacao = pd.read_csv(r'C:\Users\gusta\OneDrive\Área de Trabalho\TCC\Classificacao_2023.csv')
df_camp23_rodadas = pd.read_csv(r'C:\Users\gusta\OneDrive\Área de Trabalho\TCC\Rodadas_Realizadas_2023.csv')

In [33]:
df_camp20032022_rodadas

,Temporada,Rodada,Mandante,Visitante,Mandante Placar,Visitante Placar
0,2003,1,Guarani,Vasco,4,2
1,2003,1,Athletico-PR,Grêmio,2,0
2,2003,1,Juventude,São Paulo,2,2
3,2003,1,Cruzeiro,São Caetano,2,2
4,2003,1,Flamengo,Coritiba,1,1
...,...,...,...,...,...,...
7641,2021,38,Fortaleza,Bahia,2,1
7642,2021,38,Sport,Athletico-PR,1,1
7643,2021,38,Bragantino,Internacional,1,0
7644,2021,38,Juventude,Corinthians,1,0
7645,2021,38,Atlético-GO,Flamengo,2,0

In [34]:
TABLE_NAME = 'campeonato_brasileiro_classificacao_2003_2022'
df_camp20032022_classificacao.to_sql(TABLE_NAME, engine, index=False, if_exists='replace')

TABLE_NAME = 'campeonato_brasileiro_classificacao_2023'
df_camp23_classificacao.to_sql(TABLE_NAME, engine, index=False, if_exists='replace')

TABLE_NAME = 'campeonato_brasileiro_rodadas_2003_2022'
df_camp20032022_rodadas.to_sql(TABLE_NAME, engine, index=False, if_exists='replace')

TABLE_NAME = 'campeonato_brasileiro_rodadas_2023'
df_camp23_rodadas.to_sql(TABLE_NAME, engine, index=False, if_exists='replace')